### ISSUE TITLE
-config option in commandline

### ISSUE THREAD

**Issue by msdos** [tinyMediaManager/tinyMediaManager#370] opened 2018-08-21 09:08 UTC
In sourcecode, you check only for xml inside tmm's `data` folder. https://github.com/tinyMediaManager/tinyMediaManager/blob/master/src/main/java/org/tinymediamanager/TinyMediaManagerCMD.java#L141

Suggestion: accept a full path or change the builtin help from
```
     -config file.xml      specify an alternative configuration xml file
```
to
```
     -config file.xml      specify an alternative configuration xml file inside data folder
```

Wiki in https://github.com/tinyMediaManager/tinyMediaManager/wiki/Command-line-arguments should be updated as well. The `-config` option is only shown when `tinyMediaManagerCMD.sh` is called.

**Comment by mlaggner** [comment] 2018-08-21 10:36
possible duplicate of #126?

in fact there is more to do than just switch the config file...

**Comment by mlaggner** [comment] 2018-08-21 10:44
this cmd option is rather old and may be removed when #126 is being implemented.
until then I will change the help as you suggested

**Comment by mlaggner** [comment] 2018-08-21 10:48
changed with https://github.com/tinyMediaManager/tinyMediaManager/commit/c1fc24f74593deeb2813b900739605e2313558f4

**Closed by mlaggner** 2018-08-21 10:48 UTC
