### ISSUE TITLE
Unable to import TV shows from my NAS

### ISSUE THREAD

**Issue by Alexwijn** [tinyMediaManager/tinyMediaManager#148] opened 2017-04-30 12:03 UTC
__What TMM version are you using?__
v2.9.3.1

__release, pre-release, nightly, or directly from GitHub/branch?__
release, also tried nightly.

__What is the actual behaviour?__
Giving me a java.nio.file.FileSystemLoopException. See logs.

__What is the expected behaviour?__
Imported the TV shows successfully.

__Steps to reproduce:__
- Mount a SAMBA share on a random letter, in my case Z.
- Add the location to tMM
- Refresh the database

__Additional__
Have you attached the Logfile from the day it happened?
```13:58:51.306 WARN  org.tinymediamanager.scraper.config.MediaProviderConfig - Cannot load settings 'data\scraper_fanarttv.conf' - using defaults
13:58:51.313 WARN  org.tinymediamanager.scraper.config.MediaProviderConfig - Cannot load settings 'data\scraper_imdb.conf' - using defaults
13:58:51.424 WARN  org.tinymediamanager.scraper.config.MediaProviderConfig - Cannot load settings 'data\scraper_metadata.album.universal.conf' - using defaults
13:58:51.433 WARN  org.tinymediamanager.scraper.config.MediaProviderConfig - Cannot load settings 'data\scraper_metadata.artists.universal.conf' - using defaults
13:58:51.438 WARN  org.tinymediamanager.scraper.config.MediaProviderConfig - Cannot load settings 'data\scraper_metadata.themoviedb.org.conf' - using defaults
13:58:51.443 WARN  org.tinymediamanager.scraper.config.MediaProviderConfig - Cannot load settings 'data\scraper_metadata.album.universal.conf' - using defaults
13:58:51.448 WARN  org.tinymediamanager.scraper.config.MediaProviderConfig - Cannot load settings 'data\scraper_metadata.artists.universal.conf' - using defaults
13:58:51.454 WARN  org.tinymediamanager.scraper.config.MediaProviderConfig - Cannot load settings 'data\scraper_metadata.themoviedb.org.conf' - using defaults
13:58:51.457 WARN  org.tinymediamanager.scraper.config.MediaProviderConfig - Cannot load settings 'data\scraper_metadata.tvdb.com.conf' - using defaults
13:58:51.539 WARN  org.tinymediamanager.scraper.config.MediaProviderConfig - Cannot load settings 'data\scraper_moviemeter.conf' - using defaults
13:58:51.626 WARN  org.tinymediamanager.scraper.config.MediaProviderConfig - Cannot load settings 'data\scraper_tmdb.conf' - using defaults
13:58:57.287 ERROR o.t.core.tvshow.tasks.TvShowUpdateDatasourceTask2 - java.nio.file.FileSystemLoopException: Z:\TV Shows\Supernatural\Season 12
```

Your Operating system? Windows 10 x64

__Extra note:__
The movies works just fine. But sometimes gives the same error
`14:05:10.742 ERROR o.t.core.movie.tasks.MovieUpdateDatasourceTask2 - java.nio.file.FileSystemLoopException: Z:\Movies\Patriots Day (2016)\extrathumbs`

**Comment by myron0815** [comment] 2017-05-02 09:22
hmm.. this exception comes from following redundant links.
Eg "Z:\Movies\Patriots Day (2016)\extrathumbs" would link to "Z:\Movies\Patriots Day (2016)" and thus running into an endless loop.

Dunno what filesystem your movies are on, but check for sym/hard/junction linked folders...

**Comment by Alexwijn** [comment] 2017-05-02 09:25
I use the Shield TV as my NAS, it runs on Android TV. Also the movies are not the issue here, the TV shows are.

**Comment by ProIcons** [comment] 2017-08-01 09:54
Maybe it is a Samba Implementation issue with the Software you are running. The LoopException indicates unstable results from the Samba Service.

Please ensure your filesystem is **NOT** ReFs. If it is switch it back to NTFS. ReFs has known issues with allowing up to 100 entries.  

Also please make sure you update the firmware of Shield TV to the latest one. 

If problem persists please comment here and we will investigate further your issue. 
In any case please reproduce the problem, and send us the log file as attachment.

**Comment by Alexwijn** [comment] 2017-08-05 13:48
I'm using the latest version of the firmware and I'm sure that I do not use any ReFs since my Shield TV is not rooted. The logs are the same as the one I posted above.

**Comment by ProIcons** [comment] 2017-08-05 14:39
> Extra note:
> The movies works just fine. But sometimes gives the same error

This code is not changing. So "sometimes" indicates issues with your filesystem, or samba implementation rather, than tinyMediaManager  fault. 

Whatsoever, i will be trying to reproduce your issue. I ordered a ShieldTV, and in a Week or so i will check what is causing the issue.

**Comment by ProIcons** [comment] 2017-08-19 23:51
To assist you better, i would need your firmware version.

**Comment by Alexwijn** [comment] 2017-08-20 11:37
I'm using version 5.2(24.28.403.173).

**Comment by ProIcons** [comment] 2017-08-20 11:38
NVIDIA is Watching this Thread. They will try to check if the problem is at their end, and they will contact us. Please stay in touch, we might need more information.

**Comment by ProIcons** [comment] 2017-09-02 17:43
@Alexwijn is there any available update for your device at the moment? if so update and comeback to me, with results, if it worked or not.

**Comment by Alexwijn** [comment] 2017-09-09 08:24
I did not receive any update of Shield TV this week.

**Comment by ProIcons** [comment] 2017-09-09 08:25
Is the problem persisting?

**Comment by Alexwijn** [comment] 2017-10-01 08:27
Still the same errors, even with the latest 6.0 update.

**Comment by ProIcons** [comment] 2017-10-01 19:43
Have you updated to our latest TMM version and the latest Java version?

**Comment by Alexwijn** [comment] 2017-10-02 16:06
Same errors, I'm using TMM version 2.9.4 SNAPSHOT, build 51ba352 and java version 1.8.0_141.

**Comment by ProIcons** [comment] 2017-10-02 16:24
It's certainly a fs related error. Is not on our end. After some discussions i had with Nvidia suggested that you should contact them about this very same issue. They will assist you resolving this issue.

**Closed by ProIcons** 2017-10-02 16:24 UTC
Labels: help wanted
