### ISSUE TITLE
problems with character ² in file path

### ISSUE THREAD

**Issue by buhtz** [tinyMediaManager/tinyMediaManager#203] opened 2017-09-02 08:06 UTC
Using `v3` branch from this git-repo on Debian unstable.

When starting TMM I got an java.nio.file.InvalidPathException (I think) because there is a `²` in my file path.

- Is it a problem with a third-party java library? If so where should I report it?
- Currently it would be nice if TMM could handle (only as a workround) such exceptions without closing the application. Currently I can not run TMM because of that "simple" problem. Possible workaround: Catch such exceptions, inform the user, delete the entry in the tmm-database and go on.

```
2017-09-02 10:00:20,599 ERROR [main] org.tinymediamanager.TinyMediaManager:401 - Exception while start of tmm
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /mnt/Sparky/Media/Filme/Zombie/[REC]² (2009)/poster.jpg
	at sun.nio.fs.UnixPath.encode(UnixPath.java:147)
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.tinymediamanager.core.entities.MediaFile.getFileAsPath(MediaFile.java:509)
	at org.tinymediamanager.core.entities.MediaFile.getFile(MediaFile.java:504)
	at org.tinymediamanager.core.entities.MediaEntity.getArtworkFilename(MediaEntity.java:278)
	at org.tinymediamanager.core.movie.entities.Movie.getHasImages(Movie.java:382)
	at org.tinymediamanager.ui.movies.MovieTableFormat.lambda$new$6(MovieTableFormat.java:168)
	at org.tinymediamanager.ui.components.table.TmmTableFormat.getColumnValue(TmmTableFormat.java:55)
	at ca.odell.glazedlists.swing.DefaultEventTableModel.getValueAt(DefaultEventTableModel.java:199)
	at javax.swing.JTable.getValueAt(JTable.java:2717)
	at org.tinymediamanager.ui.components.table.TmmTable.adjustColumnPreferredWidths(TmmTable.java:156)
	at org.tinymediamanager.ui.movies.panels.MovieListPanel.initComponents(MovieListPanel.java:143)
	at org.tinymediamanager.ui.movies.panels.MovieListPanel.<init>(MovieListPanel.java:80)
	at org.tinymediamanager.ui.movies.MovieUIModule.<init>(MovieUIModule.java:117)
	at org.tinymediamanager.ui.movies.MovieUIModule.getInstance(MovieUIModule.java:190)
	at org.tinymediamanager.ui.MainWindow.initialize(MainWindow.java:429)
	at org.tinymediamanager.ui.MainWindow.<init>(MainWindow.java:132)
	at org.tinymediamanager.TinyMediaManager$1.run(TinyMediaManager.java:331)
```

**Comment by mlaggner** [comment] 2017-09-02 08:15
that is core java - dunno why it has problems with that character (imho *nix file systems are the most tolerant ones out there in case of file names)...
that's a good point to expose the problem to the user - thanks for pointing that out (btw this problem should also be in v2)

**Comment by mlaggner** [comment] 2017-09-02 08:18
just did a test and it works here?!
![filename](https://user-images.githubusercontent.com/1523778/29994107-0853e06e-8fc8-11e7-9ee0-f95de4e274a0.png)

which file system and jdk do you use? I am using EXT4 and openjdk8 here

**Comment by mlaggner** [comment] 2017-09-02 08:21
does this thread help? https://stackoverflow.com/questions/39185613/java-nio-file-invalidpathexception-malformed-input-or-input-contains-unmappable
do you have UTF8 used in your locale?

**Comment by buhtz** [comment] 2017-09-02 10:18
Mystic: Currently I am not able to reproduce the problem. No matter if the mount point is mounted or not. Of course I didn't change anything! :D Same binary, same system, no updates done, even no reboot!

Maybe the problem occured because of the mixture of tmm2.4_snapshot and tmm3.*. Both of them use the same database in user directory, right? To exotic unusual use case. If no one can reproduce this I would suggest to close the Issue and don't waste more time here. ;)

I am using ext4. `mkdir dir²` work fine.

The log says

```
2017-09-02 09:57:42,787 INFO  [main] org.tinymediamanager.TinyMediaManager:152 - =====================================================
2017-09-02 09:57:42,788 INFO  [main] org.tinymediamanager.TinyMediaManager:153 - === tinyMediaManager (c) 2012-2016 Manuel Laggner ===
2017-09-02 09:57:42,788 INFO  [main] org.tinymediamanager.TinyMediaManager:154 - =====================================================
2017-09-02 09:57:42,790 INFO  [main] org.tinymediamanager.TinyMediaManager:155 - tmm.version      : 3.0-SNAPSHOT
2017-09-02 09:57:42,790 INFO  [main] org.tinymediamanager.TinyMediaManager:156 - os.name          : Linux
2017-09-02 09:57:42,791 INFO  [main] org.tinymediamanager.TinyMediaManager:157 - os.version       : 4.12.9-towo.1-siduction-amd64
2017-09-02 09:57:42,791 INFO  [main] org.tinymediamanager.TinyMediaManager:158 - os.arch          : amd64
2017-09-02 09:57:42,791 INFO  [main] org.tinymediamanager.TinyMediaManager:159 - java.version     : 1.8.0_144
2017-09-02 09:57:42,791 INFO  [main] org.tinymediamanager.TinyMediaManager:576 - default encoding : UTF-8 | UTF8 | UTF-8
2017-09-02 09:57:42,792 INFO  [main] org.tinymediamanager.TinyMediaManager:576 - set encoding to  : UTF-8 | UTF8 | UTF-8
2017-09-02 09:57:42,792 INFO  [main] org.tinymediamanager.TinyMediaManager:188 - System language  : en_US
2017-09-02 09:57:42,792 INFO  [main] org.tinymediamanager.TinyMediaManager:189 - GUI language     : de_DE
2017-09-02 09:57:43,028 DEBUG [main] o.tinymediamanager.core.AbstractSettings:179 - Loading settings (movies.xml) from data
2017-09-02 09:57:43,045 INFO  [main] org.tinymediamanager.TinyMediaManager:190 - Scraper language : Deutsch
2017-09-02 09:57:43,109 DEBUG [main] o.tinymediamanager.core.AbstractSettings:179 - Loading settings (tvShows.xml) from data
2017-09-02 09:57:43,115 INFO  [main] org.tinymediamanager.TinyMediaManager:191 - TV Scraper lang  : Deutsch

```

There is no info about the used jdk, or not? Could be added here for the future. Because I am not sure which jdk is used here in my system.
```
$ java -version
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-8u144-b01-1-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)

```

My local
```
$ locale
LANG=de_DE.utf8
LANGUAGE=
LC_CTYPE="de_DE.utf8"
LC_NUMERIC="de_DE.utf8"
LC_TIME="de_DE.utf8"
LC_COLLATE="de_DE.utf8"
LC_MONETARY="de_DE.utf8"
LC_MESSAGES="de_DE.utf8"
LC_PAPER="de_DE.utf8"
LC_NAME="de_DE.utf8"
LC_ADDRESS="de_DE.utf8"
LC_TELEPHONE="de_DE.utf8"
LC_MEASUREMENT="de_DE.utf8"
LC_IDENTIFICATION="de_DE.utf8"
LC_ALL=

```

Just to be clear. The path-string used in the exception: The path is not mounted (would be NFS with an ext4). The string comes from tmm-database or a config file. I don't know how or where tmm stores this information.

**Comment by ProIcons** [comment] 2017-09-02 11:43
TMM v3 and v2 are using different databases. There might be a conversion from v2 to v3, but not the opposite.

**Comment by ProIcons** [comment] 2017-09-02 12:58
This issue cannot be confirmed neither on Windows 10 nor on Linux Ubuntu Subsystem for Windows

# Windows Subsystem for Linux
```
root@Atlantis:~# uname -a
Linux Atlantis 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

root@Atlantis:~# cat /proc/version
Linux version 4.4.0-43-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1-Microsoft Wed Dec 31 14:42:53 PST 2014

root@Atlantis:~# locale
LANG=en_US.UTF8
LANGUAGE=
LC_CTYPE="en_US.UTF8"
LC_NUMERIC="en_US.UTF8"
LC_TIME="en_US.UTF8"
LC_COLLATE="en_US.UTF8"
LC_MONETARY="en_US.UTF8"
LC_MESSAGES="en_US.UTF8"
LC_PAPER="en_US.UTF8"
LC_NAME="en_US.UTF8"
LC_ADDRESS="en_US.UTF8"
LC_TELEPHONE="en_US.UTF8"
LC_MEASUREMENT="en_US.UTF8"
LC_IDENTIFICATION="en_US.UTF8"
LC_ALL=

root@Atlantis:~# java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

## v2.9.3.1
```
[main] org.tinymediamanager.TinyMediaManager:151 - =====================================================
[main] org.tinymediamanager.TinyMediaManager:152 - === tinyMediaManager (c) 2012-2016 Manuel Laggner ===
[main] org.tinymediamanager.TinyMediaManager:153 - =====================================================
[main] org.tinymediamanager.TinyMediaManager:154 - tmm.version      : 2.9.3.1
[main] org.tinymediamanager.TinyMediaManager:160 - os.name          : Linux
[main] org.tinymediamanager.TinyMediaManager:161 - os.version       : 4.4.0-43-Microsoft
[main] org.tinymediamanager.TinyMediaManager:162 - os.arch          : amd64
[main] org.tinymediamanager.TinyMediaManager:164 - java.version     : 1.8.0_144
[main] org.tinymediamanager.TinyMediaManager:548 - default encoding : UTF-8 | UTF8 | UTF-8
[main] org.tinymediamanager.TinyMediaManager:548 - set encoding to  : UTF-8 | UTF8 | UTF-8
[main] org.tinymediamanager.TinyMediaManager:193 - System language  : en_US
[main] org.tinymediamanager.TinyMediaManager:194 - GUI language     : en_US
[main] org.tinymediamanager.TinyMediaManager:195 - Scraper language : English
[main] org.tinymediamanager.TinyMediaManager:196 - TV Scraper lang  : English
[tmmpool-main-task-T1-G2] o.t.c.m.tasks.MovieUpdateDatasourceTask2:161 - Start UDS on datasource: /root/movies
[tmmpool-update-T1-G3] o.t.c.m.tasks.MovieUpdateDatasourceTask2:546 - Parsing single movie directory: /root/movies/This is a ²³§τ®αng�€ Folder (are we a disc folder? false)
[tmmpool-update-T1-G3] o.t.c.m.tasks.MovieUpdateDatasourceTask2:579 - | movie not found; looking for NFOs
[tmmpool-update-T1-G3] o.t.c.m.tasks.MovieUpdateDatasourceTask2:645 - | store movie into DB as: This Is A ²³§τ®αng�€ Folder
[tmmpool-update-T1-G3] o.t.c.m.tasks.MovieUpdateDatasourceTask2:901 - | parsing VIDEO /root/movies/This is a ²³§τ®αng�€ Folder/movie.avi
[tmmpool-main-task-T1-G2] o.t.c.m.tasks.MovieUpdateDatasourceTask2:996 - removing orphaned movies/files...
[tmmpool-main-task-T1-G2] o.t.c.m.tasks.MovieUpdateDatasourceTask2:1048 - Movie (This Is A ²³§τ®αng�€ Folder) is new - no need for cleanup
```

## v3.0-SNAPSHOT
```
[main] org.tinymediamanager.TinyMediaManager:152 - =====================================================
[main] org.tinymediamanager.TinyMediaManager:153 - === tinyMediaManager (c) 2012-2016 Manuel Laggner ===
[main] org.tinymediamanager.TinyMediaManager:154 - =====================================================
[main] org.tinymediamanager.TinyMediaManager:155 - tmm.version      : 3.0-SNAPSHOT
[main] org.tinymediamanager.TinyMediaManager:156 - os.name          : Linux
[main] org.tinymediamanager.TinyMediaManager:157 - os.version       : 4.4.0-43-Microsoft
[main] org.tinymediamanager.TinyMediaManager:158 - os.arch          : amd64
[main] org.tinymediamanager.TinyMediaManager:159 - java.version     : 1.8.0_144
[main] org.tinymediamanager.TinyMediaManager:576 - default encoding : UTF-8 | UTF8 | UTF-8
[main] org.tinymediamanager.TinyMediaManager:576 - set encoding to  : UTF-8 | UTF8 | UTF-8
[main] org.tinymediamanager.TinyMediaManager:188 - System language  : en_US
[main] org.tinymediamanager.TinyMediaManager:189 - GUI language     : en_US
[tmmpool-main-task-T1-G2] o.t.c.m.tasks.MovieUpdateDatasourceTask2:159 - Start UDS on datasource: /root/movies
[tmmpool-update-T1-G3] o.t.c.m.tasks.MovieUpdateDatasourceTask2:517 - Parsing single movie directory: /root/movies/This is a ²³§τ®αng�€ Folder (are we a disc folder? false)
[tmmpool-update-T1-G3] o.t.c.m.tasks.MovieUpdateDatasourceTask2:550 - | movie not found; looking for NFOs
[tmmpool-update-T1-G3] o.t.c.m.tasks.MovieUpdateDatasourceTask2:620 - | store movie into DB as: This Is A ²³§τ®αng�€ Folder
[tmmpool-update-T1-G3] o.t.c.m.tasks.MovieUpdateDatasourceTask2:880 - | parsing VIDEO /root/movies/This is a ²³§τ®αng�€ Folder/movie.avi
[tmmpool-main-task-T1-G2] o.t.c.m.tasks.MovieUpdateDatasourceTask2:975 - removing orphaned movies/files...
[tmmpool-main-task-T1-G2] o.t.c.m.tasks.MovieUpdateDatasourceTask2:1027 - Movie (This Is A ²³§τ®αng�€ Folder) is new - no need for cleanup
```

# Windows 10 Enterprise

```
PS C:\Users\Nikolas> (Get-WmiObject win32_operatingsystem).caption
Microsoft Windows 10 Enterprise

PS C:\Users\Nikolas> Get-Host

Name             : ConsoleHost
Version          : 5.1.15063.502
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : el-GR
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

PS C:\Users\Nikolas> Get-UICulture

LCID             Name             DisplayName
----             ----             -----------
1033             en-US            English (United States)

PS C:\Users\Nikolas> systeminfo

Host Name:                 ATLANTIS
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.15063 N/A Build 15063

PS C:\Users\Nikolas> java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) Client VM (build 25.144-b01, mixed mode, sharing)
```

## v2.9.4-SNAPSHOT
```
[main] org.tinymediamanager.TinyMediaManager:151 - =====================================================
[main] org.tinymediamanager.TinyMediaManager:152 - === tinyMediaManager (c) 2012-2016 Manuel Laggner ===
[main] org.tinymediamanager.TinyMediaManager:153 - =====================================================
[main] org.tinymediamanager.TinyMediaManager:154 - tmm.version      : 2.9.4-SNAPSHOT
[main] org.tinymediamanager.TinyMediaManager:160 - os.name          : Windows 10
[main] org.tinymediamanager.TinyMediaManager:161 - os.version       : 10.0
[main] org.tinymediamanager.TinyMediaManager:162 - os.arch          : amd64
[main] org.tinymediamanager.TinyMediaManager:164 - java.version     : 1.8.0_144
[main] org.tinymediamanager.TinyMediaManager:548 - default encoding : UTF-8 | UTF8 | UTF-8
[main] org.tinymediamanager.TinyMediaManager:548 - set encoding to  : UTF-8 | UTF8 | UTF-8
[main] org.tinymediamanager.TinyMediaManager:193 - System language  : en_US
[main] org.tinymediamanager.TinyMediaManager:194 - GUI language     : en_US
[main] org.tinymediamanager.TinyMediaManager:195 - Scraper language : Ελληνικά
[main] org.tinymediamanager.TinyMediaManager:196 - TV Scraper lang  : English
[main] org.tinymediamanager.TinyMediaManager:224 - =====================================================
[tmmpool-update-T1-G236] o.t.c.m.tasks.MovieUpdateDatasourceTask2:549 - Parsing single movie directory: W:\Store\Movies\2017\This is a ²³£§ Sτ®αng€ folder (are we a disc folder? false)
[tmmpool-update-T1-G236] o.t.c.m.tasks.MovieUpdateDatasourceTask2:648 - | store movie into DB as: This Is A ²³£§ Sτ®αng€ Folder
[tmmpool-update-T1-G236] o.t.c.m.tasks.MovieUpdateDatasourceTask2:904 - | parsing VIDEO W:\Store\Movies\2017\This is a ²³£§ Sτ®αng€ folder\movie.avi
```

## v3.0-SNAPSHOT
```
[main] org.tinymediamanager.TinyMediaManager:152 - =====================================================
[main] org.tinymediamanager.TinyMediaManager:153 - === tinyMediaManager (c) 2012-2016 Manuel Laggner ===
[main] org.tinymediamanager.TinyMediaManager:154 - =====================================================
[main] org.tinymediamanager.TinyMediaManager:155 - tmm.version      : 3.0-SNAPSHOT
[main] org.tinymediamanager.TinyMediaManager:156 - os.name          : Windows 10
[main] org.tinymediamanager.TinyMediaManager:157 - os.version       : 10.0
[main] org.tinymediamanager.TinyMediaManager:158 - os.arch          : amd64
[main] org.tinymediamanager.TinyMediaManager:159 - java.version     : 1.8.0_144
[main] org.tinymediamanager.TinyMediaManager:576 - default encoding : UTF-8 | UTF8 | UTF-8
[main] org.tinymediamanager.TinyMediaManager:576 - set encoding to  : UTF-8 | UTF8 | UTF-8
[main] org.tinymediamanager.TinyMediaManager:188 - System language  : en_US
[main] org.tinymediamanager.TinyMediaManager:189 - GUI language     : en_US
[main] o.tinymediamanager.core.AbstractSettings:179 - Loading settings (movies.xml) from data
[main] org.tinymediamanager.TinyMediaManager:190 - Scraper language : Ελληνικά
[main] o.tinymediamanager.core.AbstractSettings:179 - Loading settings (tvShows.xml) from data
[main] org.tinymediamanager.TinyMediaManager:191 - TV Scraper lang  : English
[main] org.tinymediamanager.TinyMediaManager:219 - =====================================================
[tmmpool-update-T6-G236] o.t.c.m.tasks.MovieUpdateDatasourceTask2:517 - Parsing single movie directory: W:\Store\Movies\2017\This is a ²³£§ Sτ®αng€ folder (are we a disc folder? false)
[tmmpool-update-T6-G236] o.tinymediamanager.core.movie.MovieList:425 - Ok, found already existing movie 'This Is A ²³£§ Sτ®αng€ Folder' in DB (path: W:\Store\Movies\2017\This is a ²³£§ Sτ®αng€ folder)
[tmmpool-update-T6-G236] o.t.c.m.tasks.MovieUpdateDatasourceTask2:620 - | store movie into DB as: This Is A ²³£§ Sτ®αng€ Folder
```

**Comment by mlaggner** [comment] 2017-09-02 14:02
may I close this issue since you can't reproduce it anymore?

**Closed** 2017-09-02 14:28 UTC
