### ISSUE TITLE
ArtworkDownload

### ISSUE THREAD

**Issue by AGATHOKL3S** [tinyMediaManager/tinyMediaManager#392] opened 2018-09-17 01:08 UTC
Version: 2.9.13
Build: 2018-07-23 18:42
OS: Windows 10 10.0
JDK: 1.8.0_181 amd64 Oracle Corporation

__What is the actual behaviour?__
Error at downloading Artwork : Error accessing url: Internal Server Error
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2387177/tmm_logs.zip)

__What is the expected behaviour?__

__Steps to reproduce:__

__Additional__
Have you attached the logfile from the day it happened?
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2387179/tmm_logs.zip)

**Comment by myron0815** [comment] 2018-09-17 06:04
Well, some of the Fanart.tv downloadservers have expired HTTPS SSL certificates.
> CertificateExpiredException: NotAfter: Tue Jun 12 12:25:05 CEST 2018
There's nothing we can do about - we're already retrying 5 times...

**Comment by mlaggner** [comment] 2018-09-17 06:43
duplicate of #373

**Closed by mlaggner** 2018-09-17 06:43 UTC
