### ISSUE TITLE
Problem of re-scraping extra graphics

### ISSUE THREAD

**Issue by Zwanzig2** [tinyMediaManager/tinyMediaManager#282] opened 2018-04-21 09:01 UTC
Version: 2.9.9-SNAPSHOT - NIGHTLY
Build: 2018-04-20 23:03
OS: Windows 7 6.1
JDK: 1.8.0_161 amd64 Oracle Corporation

Hello
Unfortunately, I need to re-open the extrafanart case. I understand that there is a problem with the fanarttv API but I do not quite often download even from Moviedb. As I wrote before, it seems that if TMM encounters a problem with downloading from fanarttv, it does not download any more. It can at least do that if there is no answer after a certain time, the next fanart is downloaded.
In addition, if the download has already occurred (even if nothing has been downloaded) I can not retry - TMM does not download again. I need to remove the video from the database, read it again - and only now I try again. Sometimes 3-5 times and every time I have to check in the folder if something is. It is very tedious. The problem of re-scraping also applies to other extra graphics.

[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/1934334/tmm_logs.zip)

**Comment by mlaggner** [comment] 2018-04-22 07:11
sorry, I cannot reproduce your issue.
please provide an exact description how you get extra fanart (exactly all steps you do)

all tests here worked (also with http 500 from fanart.tv); refetching extra artwork from fanart.tv worked too..

**Comment by Zwanzig2** [comment] 2018-04-22 09:09
I do not know if it will be understandable. Unfortunately, I do not speak English, so I help myself with a translator.
One of the examples:
1. Movie information already downloaded (not downloaded all graphics)
![1](https://user-images.githubusercontent.com/23637884/39093299-55742014-461d-11e8-9dc7-a42e7564ab56.jpg)

2. Edits the movie - extra graphic
![2](https://user-images.githubusercontent.com/23637884/39093301-69cf75cc-461d-11e8-84f7-d72b8b9cfc7f.jpg)

3. I download the missing
![3](https://user-images.githubusercontent.com/23637884/39093303-71d2fdde-461d-11e8-8d05-01e41ad5e072.jpg)

4. press OK
5. does not download (no progress bar is shown)
![4](https://user-images.githubusercontent.com/23637884/39093306-7a508fa8-461d-11e8-9a1b-69079d3a7ca0.jpg)

----------
6. I remove a movie from the database
7. I'm loading again
8. I repeat points 2-4 (the download progress bar appears - ie it downloads but of course not always successfully).
If the download fails - it takes 2-5, and I repeat 6-8 :)
Over and over again.
If the download succeeds I can edit the movie and change the graphics to another one if I need one.
If I can not download, I can not continue to edit the graphics in this movie without deleting it from the database and reloading it.

I still have the same problem I described in # 278. If you do not download extra fanart - the same situation as described above

**Comment by mlaggner** [comment] 2018-04-23 05:27
okay, now I see your problem. 
this issue has already been addressed in v3 and I probably won't backport that to v2

but for your case (where no artwork is available) I could insert a little hack

**Comment by mlaggner** [comment] 2018-04-23 05:42
the main problem here is, that tmm knows the right url of the artwork from the image chooser but fails to download it. (btw: we can't reuse the artwork from the image chooser because that is loaded in a much smaller resoultion to save network resources)..
after that if you go into the movie editor again, tmm sees no difference between the old and the new artwork url and does not trigger the download again;
with the little hack I also check if at least one artwork of that type is assigned to the movie and if not, the download will be triggered

**Comment by Zwanzig2** [comment] 2018-04-23 06:36
Actually, I will slowly go to version 3.
I also noticed that if I search for information about a new movie and set up to have automatic downloading of graphics - the problem occurs sporadically (or not at all?) (It downloads all graphics). If in the settings I have to manually select graphics, it is a tragedy - both for newly added movies and re-loading graphics in films that are already in the database.
Thanks for your interest and work :)

**Comment by Zwanzig2** [comment] 2018-04-24 00:26
Ok, it looks like the "hack" works

**Closed** 2018-05-02 11:10 UTC
Labels: bug, enhancement
