### ISSUE TITLE
Cannot exlude a sub-directory of the movies search

### ISSUE THREAD

**Issue by metivier** [tinyMediaManager/tinyMediaManager#40] opened 2016-06-13 19:54 UTC
**What TMM version are you using?**
2.8

**release, pre-release, nightly, or directly from GitHub/branch?**
release

**What is the actual behaviour?**
All the movies appear in the movies list.

**What is the expected behaviour?**
The movies from the subdirectory added in the "folder to exclude" must not be visible.

**Steps to reproduce:**
- add a movie folder (ex: c:/foo )
- add a movie subfolder in the exclusion (c:/foo/bar )
- the movies in the folder c:/foo/bar must not be present in the movies view.

**Additional**
Your Operating system : windows 10

**Comment by mlaggner** [comment] 2016-06-14 05:28
is working here..
do you have any concrete example? (file listing and config.xml)

**Comment by myron0815** [comment] 2016-06-14 16:23
HOW did you perform the update?
Update all datasources (with the big button), or just a single chosen one?
Because the latter had an error which has been fixed with e52ee216ab89e1d3b2b5ec0901ccbbcfdb91e968

**Comment by metivier** [comment] 2016-06-20 11:44
Hi,

I just click the button refresh all datasources, with the big button with the "reload loop arrow" icon.

I update to the 2.8.1 version yesterday, and the same thing appears (the excluded sub-folder is not excluded).
I solve my issue moving my sub-folder to another place (but it's a bypass, not a fix).

Thanks for reactivity.

**Comment by mlaggner** [comment] 2016-07-08 06:08
still cannot reproduce. Please try to add a `.tmmignore` or `tmmignore` file in the folders to exclude

**Closed** 2016-11-20 10:00 UTC
Labels: bug
