### ISSUE TITLE
Error switching from the Details tab to Details 2

### ISSUE THREAD

**Issue by Zwanzig2** [tinyMediaManager/tinyMediaManager#252] opened 2018-01-26 20:54 UTC
Version: 2.9.8-SNAPSHOT - NIGHTLY
Build: 2018-01-23 00:03
OS: Windows 7 6.1
JDK: 1.8.0_161 amd64 Oracle Corporation

Hello
I get an error when switching from the Details tab to Details 2 (Edit Movie).
I'm breaking the log

[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/1669156/tmm_logs.zip)

**Comment by myron0815** [comment] 2018-01-27 09:43
works for me.
Need to check what causes this.
thx

**Comment by mlaggner** [comment] 2018-01-27 10:08
are you able to reproduce that?

**Comment by Zwanzig2** [comment] 2018-01-27 10:49
I did not describe the problem exactly, I thought that after the log you will know - Sorry.
It does not always happen, only sometimes. I have not yet established the regularity.
It is possible that this is something in my system and not in the TMM.
I attach Screen and info from the window.
![tmm](https://user-images.githubusercontent.com/23637884/35471245-9f3a11c6-0357-11e8-9b7d-b77997de3cb6.jpg)
[problem.txt](https://github.com/tinyMediaManager/tinyMediaManager/files/1669999/problem.txt)

**Comment by mlaggner** [comment] 2018-01-27 12:01
nothing useful visible in that stacktrace :(
could you send us your database file (data/movies.db - please zipped) to support@tinymediamanager.org ?

**Comment by myron0815** [comment] 2018-01-28 14:58
Since it has something to do with visibility...
...try deleting (renaming) the `data/tmm.prop` file.
(will reset all your window preferences to default)
Does it happen again?

**Comment by nafets83** [comment] 2018-01-29 16:15
I can confirm this bug. I got Version 2.9.7 (28.12.2017)
The error is hard to reproduce. I will update my Java.

**Comment by Zwanzig2** [comment] 2018-01-30 15:19
unfortunately, deleting the file does not help, and the newer java is not there

**Comment by Zwanzig2** [comment] 2018-01-31 09:38
Thanks
It works but unfortunately there are some other programs that are based on java 8 :(

**Comment by mlaggner** [comment] 2018-01-31 10:02
as far as I could read out of the openjdk bug report, this should be fixed in the next java 8 patch

**Comment by Zwanzig2** [comment] 2018-01-31 14:01
I found the version java 8 update 162, but nothing changes.
Actually, in the program I can continue working, the dialog can be closed, the program remains running. The error appears again after searching for the next movie.

**Comment by Zwanzig2** [comment] 2018-04-26 07:16
Hello
I upgraded jave to version 8 update 171 and it looks like the problem has been solved but please check again

**Closed** 2018-05-01 07:31 UTC
Labels: bug, processing
